### ISSUE TITLE
libvirt installation failed

### ISSUE THREAD

**Issue by theraw** [tigerlinux/openstack-pike-installer-ubuntu1604lts#1]
hello

Thank you for this script, i have one question, what does this check https://github.com/tigerlinux/openstack-pike-installer-ubuntu1604lts/blob/master/modules/requeriments.sh#L268 ?!

i tried to install but i stuck because of it the result of that check is 0 *(tried in 3 different machines the same output 0)*, but libvirt is running
```bash
FINAL LIBVIRTD CHECK:
Setting /etc/apparmor.d/usr.sbin.libvirtd to complain mode.
● libvirt-bin.service - Virtualization daemon
   Loaded: loaded (/lib/systemd/system/libvirt-bin.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-12-10 02:58:40 CET; 3ms ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 23792 (libvirtd)
   CGroup: /system.slice/libvirt-bin.service
           ├─23792 /usr/sbin/libvirtd
           └─23810 /usr/sbin/libvirtd

Dec 10 02:58:40 kvm2 systemd[1]: Starting Virtualization daemon...
Dec 10 02:58:40 kvm2 systemd[1]: Started Virtualization daemon.


Libvirt installation FAILED. Aborting !

Something bad happened. Validations failed
Aborting the installation !!
```

**Comment by tigerlinux** [comment]
Hi there,

The right services that my installer "installs" is "libvirtd.service" (not libvirt-bin.service). Also, and to be completely sure, I ran again my installer on a clean machine (with the official openstack-pike repos from ubuntu-cloud-archive). From Ocata the "libvirtd.service" is being used instead libvirt-bin so I suggest you check again what repos are you using.

**Comment by theraw** [comment]
```
FINAL LIBVIRTD CHECK:
Setting /etc/apparmor.d/usr.sbin.libvirtd to complain mode.
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-12-10 16:45:51 CET; 5ms ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 29827 (libvirtd)
    Tasks: 17 (limit: 32768)
   Memory: 3.9M
      CPU: 40ms
   CGroup: /system.slice/libvirtd.service
           └─29827 /usr/sbin/libvirtd --listen

Dec 10 16:45:51 vps490785 systemd[1]: Starting Virtualization daemon...

Libvirt correctly installed


Requeriments installed and initial validations done
I'll continue with the OpenStack modules installation

Ready... let's continue working
```
Thank you !

**Comment by tigerlinux** [comment]
heeh then it was a bad repo right?..

**Comment by theraw** [comment]
yes, this is my first time trying to setup OpenStack :v:

**Comment by theraw** [comment]
@tigerlinux sorry to disturb you, But i have a question
i'm running controller in one small server, where i have install database, keystone, rabbitmq horizon and glance..

But now i'm trying to add a compute to my controller (a dedicated server) , but while reading openstack docs first think to install is nova?, i was seeing your script but the `novainstall.sh` will try to verify if database and keystone are installed, are they needed to be installed in compute?
![image](https://user-images.githubusercontent.com/32969774/33909707-d28655ba-df8c-11e7-9650-c04e50524a86.png)
